import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  scrollContainer: {
    flex: 1,
    backgroundColor: "white",
  },
  container: {
    backgroundColor: "white",
    padding: 16,
    paddingTop: height * 0.05,
    alignItems: "center",
    minHeight: height,
  },
  progressContainer: {
    marginVertical: 10,
  },
  cardsContainer: {
    padding: 16,
    gap: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    backgroundColor: "white",
    width: width * 0.96,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  cardContainer: {
    backgroundColor: "white",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 16,
    overflow: "hidden",
    width: width * 0.9,
    height: height * 0.25,
  },
  cardContent: {
    padding: 20,
    paddingBottom: 0,
  },
  iconRow: {
    flexDirection: "row",
    marginVertical: 16,
    gap: 24,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#F7F9F8",
    justifyContent: "center",
    alignItems: "center",
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: "SatoshiBold",
    color: "#1F2937",
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    fontFamily: "Satoshi",
  },
  previewButton: {
    borderWidth: 1,
    borderColor: "#000",
    borderRadius: 8,
    padding: 10,
    alignItems: "center",
    width: width * 0.8,
    alignSelf: "center",
    marginBottom: 16,
  },
  previewButtonText: {
    color: "#000",
    fontSize: 13,
    fontFamily: "SatoshiBold",
  },
  title: {
    fontSize: 17,
    fontFamily: "SatoshiBold",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 13,
    color: "#6B7280",
    fontFamily: "Satoshi",
    marginBottom: 24,
  },
  continueButton: {
    backgroundColor: "#8BAA9E",
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 24,
    marginBottom: 24,
    width: width * 0.8,
    alignSelf: "center",
  },
  buttonText: {
    fontSize: 16,
    fontFamily: "SatoshiBold",
    color: "white",
  },
  infoContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 24,
    backgroundColor: "#F7F9F8",
    padding: 10,
    borderRadius: 8,
  },
  infoText: {
    fontSize: 14,
    color: "#6B7280",
    fontFamily: "Satoshi",
    marginLeft: 8,
  },
  progressBar: {
    height: 4,
    backgroundColor: "#E5E7EB",
    borderRadius: 2,
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  progress: {
    height: "100%",
    backgroundColor: "#22C55E",
    borderRadius: 2,
  },
});
